mkdir projectsNew
cd projectsNew
mkdir personal_websiteNew
cd personal_websiteNew
touch index.html 
cd ..
mkdir tic_tac_toeNew
cd tic_tac_toeNew
touch tic_tac_toeNew.js
cd ..
mkdir helloNew
cd helloNew 
touch hello1.js 
touch hello2.js